Crown-Commercial-Service/digitalmarketplace-search-api

application.py

For development we will want to run multiple apps, so they should each bind to a different port number.

Update to run on port 5001

---

application.py
config.py

Renames environments to match AWS deployment stages

Use DM_ENVIRONMENT to select config environment

---

app/main/services/search_service.py
app/main/views/search.py
app/static/explorer.js
app/templates/explorer.html
tests/app/views/test_search.py

Added fetch by id and delete by id API endpoints.
Delete is needed so that we can remove from the index services which are no longer visible to the pubic.

Added delete and fetch by service ID methods, tests and explorer pages.

---

app/main/services/query_builder.py
app/main/services/response_formatters.py
app/main/services/search_service.py
app/main/views/search.py
config.py
tests/app/services/test_query_builder.py
tests/app/views/test_search.py

Added page and page_size to the query builder.
- page_size controls how much services should be returned in each page (Configured in the app config)
- page specifies which page of results should be returned

Page size and pagination

---

app/main/services/search_service.py
app/main/views/search.py
tests/app/views/test_search.py

This continues the refactoring that was started in
https://github.com/alphagov/digitalmarketplace-search-api/pull/32

Use tuple expansion

---

tests/app/views/test_search.py

To check the outputted HTML fits our assumptions.

Add a test for the highlight formatting

---

app/static/explorer.js
app/templates/explorer.html

Adds page to the explorer for testing

Added page to explorer page

---

requirements.txt

This includes:
- alphagov/digitalmarketplace-utils#171
- alphagov/digitalmarketplace-utils#169
- alphagov/digitalmarketplace-utils#167
- alphagov/digitalmarketplace-utils#170
- alphagov/digitalmarketplace-utils#166
- alphagov/digitalmarketplace-utils#164
- alphagov/digitalmarketplace-utils#163
- alphagov/digitalmarketplace-utils#162
- alphagov/digitalmarketplace-utils#161
- alphagov/digitalmarketplace-utils#160
- alphagov/digitalmarketplace-utils#159
- alphagov/digitalmarketplace-utils#158
- alphagov/digitalmarketplace-utils#156
- alphagov/digitalmarketplace-utils#155
- alphagov/digitalmarketplace-utils#154
- alphagov/digitalmarketplace-utils#153

Upgrade dmutils to 8.1.1

---

requirements.txt

This includes:
- alphagov/digitalmarketplace-utils#172

Upgrade dmutils to 8.1.2

---

application.py
config.py
requirements.txt

Adds the logging changes added in dmutils 21.0.0, which allow us to log to stdout in PaaS environments

Update dmutils to 25.0.1

---

app/main/services/process_request_json.py
app/mapping.py
mappings/services.json
tests/app/services/test_process_request_json.py

Transformation of service content before indexing, for category field.
- allows any number of transformations to be applied to the passed-in
service data before it is indexed;
- in principle this kind of thing could be an Elasticsearch 'processor'
but there does not appear to be a suitable built-in, and a custom
processor is beyond the scope of this work.
- mapping generated from framework data

Categories transformation

---

mappings/services.json

Updates the services.json mapping to include derived categories for g-cloud-9 cloud support.
https://github.com/alphagov/digitalmarketplace-frameworks/pull/419
https://trello.com/c/2x5jemYQ/340-make-support-questions-into-categories

Add derived categories for G9 cloud support

---

mappings/services.json
tests/app/services/test_query_builder.py

Update search mapping to pull in the 'serviceDescription' field from for G9 services.

Update search mapping

---

mappings/services.json

- more/different filters to follow
https://trello.com/c/vZP7vbGP/412-labelling-of-filters

These new filters for G9 are for temporary demo purposes.

---

app/main/services/process_request_json.py
mappings/services.json

Updated search filters per Frameworks PR #431.
https://trello.com/c/3XUKd0tX/345-add-filters-to-search-results-page

Updated g9 filters

---

mappings/services.json

Updated mapping from frameworks 8.4.4 / https://github.com/alphagov/digitalmarketplace-frameworks/pull/438

Latest from frameworks 8.4.4

---

mappings/services.json
tests/app/services/test_query_builder.py

https://trello.com/c/pTwwL1ht/466-index-lot-names-for-services

From frameworks (G9) v8.4.11, lot names are to be indexed.

---

Dockerfile

Pull in latest Dockerfile version to avoid breaking on long URLs.

Bump dockerfile version

---

README.md

Having just reinstalled everything from scratch, need to update this slightly for the quickstart.

Update readme for accurate reinstallation

---

mappings/briefs-digital-outcomes-and-specialists-2.json
tests/app/views/test_meta.py

Adds mapping generated by https://github.com/alphagov/digitalmarketplace-frameworks/pull/484

add dos2 briefs mapping as generated by frameworks repo

---

README.md

Following on from the updates to the manual: https://github.com/alphagov/digitalmarketplace-manual/pull/77
- Explains when and how to use the indexing and aliasing scripts
- Removes the old instructions for posting directly to the Search API endpoint. If these are deemed to still be useful I can keep them in but they seem... error prone? And G-Cloud specific.

Update README to describe scripts for ES indexing/aliasing

---

mappings/services-g-cloud-10.json
tests/app/views/test_meta.py

Probably[ for this trello card.](https://trello.com/c/Ff6wYrRG)
Includes an increased `max_result_window`. This is because we have over
20000 services for G10. Without this value being increased we would only
show that we had 20000 services.

Add search mapping for G10

---

requirements-app.txt
requirements.txt

This should bring some generic logging niceness.

digitalmarketplace-utils dependency: bump to 40.6.1

---

app/main/services/search_service.py
app/main/views/meta.py
app/mapping.py

https://trello.com/c/hKoZ6Byo/132-add-wrapper-to-log-duration-of-es-calls-in-the-search-api

132 add wrapper to log duration of es calls in the search api

---

app/main/services/search_service.py
app/main/views/meta.py
app/mapping.py

Reverts alphagov/digitalmarketplace-search-api#169 without trailing comma that was causing bugs

Revert "Revert "132 add wrapper to log duration of es calls in the search api""

---

Dockerfile

General security up-to-date-ness

Bump docker base image to 4.0.0

---

app/mapping.py

At some point between 5.4 and 5.6 (probably [this commit][1]) Elasticsearch stopped returning an empty response for a bad doc type and started returning a 404.
This commit fixes the get_mapping function so it correctly detects the case where a 404 has been raised due to a bad doc type, put still passes the exception up the chain if not so it can be handled by the `core_search_and_aggregate` function.
I discovered this when running the unit tests locally against Elasticsearch 5.6.15; it didn't come up in Travis unit tests because I forgot to upgrade Travis Elasticsearch in #189 😱 
I decided to leave in the logic to catch the old behaviour just in case (and so test will pass without #192), I'm happy to take it out if people prefer.
[1]: …

Add NotFoundError exception handler for get_mapping

---

tests/app/views/test_search.py

We rely heavily on the Elasticsearch highlighting engine in the buyer frontend, as we show the highlighted text in search results always (regardless of whether any search terms were matched) and we use its HTML escaping method as a form of protection against XSS.
However, our tests of the highlighted response have not kept up-to-date, so this PR shows them a little love.
Tests of the highlighted service description have been moved from `test_search.py` to their own file, `test_highlight.py`, and significantly rewritten and expanded.
The aim of this was to make the tests more clearly reflect our requirements of the highlight field, and make sure that any changes brought in by [Elasticsearch 6](https://trello.com/c/BlYurEoJ/418-prepare-search-api-for-elasticsearch-6) are caught.

Refactor tests of highlighting

---

Dockerfile

Pull in fix in from alphagov/digitalmarketplace-docker-base#49.

Update digitalmarketplace/base-api from 4.4.3 to 4.4.4

---

app/main/views/update.py
config.py
tests/app/views/test_update.py

* Check doc type on update methods to ensure operation on relevant documents
* Update test with realistic url and non-realistic id
https://trello.com/c/3hX9puGU/756-search-api-bug-will-allows-developers-to-delete-aliases

756-search-api-bug-will-allows-users-to-delete-aliases

---

app/main/services/search_service.py

I forgot about briefs :scream:

Add fix for highlighting briefs

---

app/__init__.py
app/metrics.py
requirements-app.txt
requirements.txt
tests/app/test_metrics.py
tests/helpers.py

https://trello.com/c/5QgsYc8V/428-put-metrics-on-search-api
Bring in new utils for metrics code
Add env var mock to Base test class to set PROMETHEUS_METRICS_PATH en…  …
Add standard tests for metrics
Add metrics to dm-search-api

428-put-metrics-on-search-api

---

mappings/services-g-cloud-11.json
tests/app/views/test_meta.py

Don't think there are any changes from the G10 mapping, but it feels safer to have a new mapping for the new services just in case.

G11 services search mapping

---

mappings/services-g-cloud-12.json
tests/app/views/test_meta.py

Trello: https://trello.com/c/fLPkfKK6/362-1-index-new-services-to-elasticsearch
Following the procedure in the manual (https://alphagov.github.io/digitalmarketplace-manual/content-and-frameworks/adding-frameworks.html#create-a-new-search-mapping-g-cloud-only)

Create search mapping for g-cloud 12

---

app/main/services/response_formatters.py
app/main/services/search_service.py
example_es_responses/briefs_index_info.json
example_es_responses/search_results.json
example_es_responses/services_index_info.json
example_es_responses/stats.json
tests/app/services/test_response_formatters.py
tests/app/views/test_status.py

TIcket: https://trello.com/c/Yh8uyxvF/2102-migrate-elasticsearch-on-preview
A few Elasticsearch 7 fixes that were missed from #272 
- The status endpoint was missing some information since it was looking in the wrong location
- The example Elasticsearch responses weren't updated for Elasticsearch 7

Elasticsearch 7 fixes
