Crown-Commercial-Service/digitalmarketplace-search-api

- .gitignore
- README.md
- app/main/search_result_formatters.py
- app/main/search_service.py
- app/main/views.py
- requirements.txt
- tests/app/test_application.py
Adds a single /search endpoint that requires 'q=<query_string>' parameter for the query string, with optional further parameters to specify filters (e.g. "&lot=iaas")
> Make search-api hit elasticsearch

- scripts/index-g6-in-elasticsearch.py
This script should have moved when the search-api was split off from the buyer-frontend app.
> Move ElasticSearch import script from buyer-frontend into search-api

- .ebextensions/wsgipassauth.config
The search-api now has proper authentication, so we need to pass the auth headers through to the app.
This is the same as how it is done in the api project:
https://github.com/alphagov/digitalmarketplace-api/blob/master/.ebextensions/wsgipassauth.config
> Pass Auth headers through to application

- app/main/services/search_service.py
Currently some error handling code tries to get `exception.info["error"]` but
for some types of exception `exception.info` is a list, not a map, so this results in:
`TypeError: sequence index must be integer, not 'str'`
when reporting errors, and the original error message is lost.
This adds a method that should ensure that there is some message to include for error
reporting, without causing a further error to be thrown.
> Fix type error caused by error reporting

- .ebextensions/wsgipassauth.config
Default elasticbeanstalk apache config doesn't set WSGIPassAuthorization,
which means that Authorization header isn't forwarded to the app,
so we need a way to modify the config ourselves. Unfortunately, there's
no documented way to do this.
Our previous solution used a container_command to add a line to
wsgi.conf. This works for deployments, but configuration changes
triggered through the AWS interface or Cloudformation updates
rewrite the wsgi.conf without executing container commands, so we needed
to run a redeploy immediately after config change to fix the PassAuth.
There's another solution described in http://stackoverflow.com/a/29031663
that patches the elasticbeanstalk code responsible for generating the
apache config. While that fixes the configuration change issue, the
solution …
> Replace wsgipassauth cmd with elasticbeanstalk config/deploy hook

- app/main/services/response_formatters.py
- app/status/views.py
Update the `_status` endpoint to indicate a connection to elasticsearch.
Everything going well returns something like this:
```json
{
"db_status": {
"message": [
{
"num_docs": 16423, 
"primary_size": "26mb"
}
], 
"status_code": 200
}, 
"status": "ok", 
"version": null
}
```
Elasticsearch not connected, but API still running:
```json
{
"db_status": {
"message": "Connection aborted.", 
"status_code": 500
}, 
"message": "Error connecting to elasticsearch", 
"status": "error", 
"version": null
}
```
And, obviously, if the API isn't running then nothing happens.
> Pc database info in status

- app/main/services/query_builder.py
- example_es_responses/search_results.json
- mappings/services.json
- tests/app/services/test_query_builder.py
- tests/app/services/test_response_formatters.py
- tests/app/views/test_search.py
this pull request adds framework name to the search index and returns it in a search result.
this is so we can render this on a search results page without hitting the data API for each service.
Requires the following 2 pull requests to be merged in order for this to be viable.
https://github.com/alphagov/digitalmarketplace-utils/pull/26
https://github.com/alphagov/digitalmarketplace-api/pull/116
Part of: https://www.pivotaltracker.com/story/show/94070088
> Indexing framework name

- app/main/services/query_builder.py
We already have a HTML pattern for [highlighting in
search results]
(http://alphagov.github.io/digitalmarketplace-frontend-toolkit/search-result.html) in the Digital Marketplace Front-end 
toolkit. This makes Elasticsearch output to that pattern.
> Make the tags for highlighting match our pattern

- tests/app/views/test_search.py
The pull request #35 failed when merged into master because the time
package is no longer imported. Newer tests have been written using the
`refresh` method instead.
> Fix test failure on master

- app/main/services/search_service.py
- app/status/views.py
- requirements_for_test.txt
- tests/app/views/test_status.py
In https://github.com/alphagov/digitalmarketplace-search-api/pull/34 I changed the way the search service functions returned multiple responses. However, I forgot to make the required change in the status view.
I've also added a minimal test of the status endpoint.
> Fix broken status endpoint

- app/main/services/search_service.py
This was no longer going through status_for_index and therefore was not
stripping down the ES result.
> Fix status_for_all_indexes

- config.py
- scripts/run_tests.sh
- tests/app/helpers.py
- tests/app/views/test_search.py
- tests/app/views/test_search_queries.py
https://www.pivotaltracker.com/story/show/93997310
Creates a new module for query tests: app/views/test_search_queries.py.
Module contains module-level setup and teardown functions that populate
the index with a large list of services for query tests.
Since setup and teardown take a long time they're run only once and
all tests use the same index contents, so no modifying/indexing
requests should be made by the module tests.
Query tests are written using nose test generators and a number of
helper functions.
Query results are verified using expected result counts and checks
that verify whether all result field values match a given predicate.
Other helper functions can be added to support checks for different
query types.
> Add search filter tests

- app/main/services/query_builder.py
- tests/app/services/test_query_builder.py
- tests/app/views/test_search_queries.py
Completes:
https://www.pivotaltracker.com/story/show/94571350
Which is to update keyword search.
This pull request enables Lucene query parsing on the search.
https://www.elastic.co/guide/en/elasticsearch/reference/1.x/query-dsl-query-string-query.html
This means we can:
- Do OR searching (for OR chicken)
- Do phrase searching ("fox eats chicken")
- Do negated searching (fox -farmer)
These 3 search types are the most common "advanced" searches on the digital marketoplace, and as such have tests written to ensure that they work as expected. This is NOT to ensure that lucence parsing works, it's more so that if the query type changes such that these types of search don't work then we know.
By default the search is and AND search - more terms narrows the search.
"default_operator": "and" …
> Keyword search improvements

- app/main/services/response_formatters.py
- app/main/services/search_service.py
- app/main/views/search.py
- config.py
- tests/app/services/test_response_formatters.py
- tests/app/views/test_search.py
- tests/app/views/test_search_queries.py
See this story in Pivotal: https://www.pivotaltracker.com/story/show/94576802 - the main aim is to make API response formats consistent across the Data and Search APIs.
There are FOUR related pull-requests to complete this story.  The other three are:
https://github.com/alphagov/digitalmarketplace-api/pull/132
https://github.com/alphagov/digitalmarketplace-utils/pull/39
https://github.com/alphagov/digitalmarketplace-buyer-frontend/pull/60
Changes in the search API are to pull out search metadata into the 'meta' element, making the 'services' element at the same level as in the data API's services response.
See these gists for examples of the new API responses:
[Example services data API response](https://gist.github.com/TheDoubleK/0d7cd9363440e700a50d)
[Example suppliers data API …
> [#94576802] Update Json api format

- app/main/services/query_builder.py
- tests/app/services/test_query_builder.py
- tests/app/views/test_search_queries.py
[#96078646](https://www.pivotaltracker.com/story/show/96078646)
Fixes error responses caused by search requests with the invalid
lucene query syntax by using the simplified query type that only
supports the basic operators and discards invalid parts of the
query instead of throwing an exception.
simple_query_string is configured to support AND, OR, NOT and quote
operators.
Unlike query_string it doesn't seem to support the dis_max query,
which might change the result order. It's hard to say how much this
will affect the results, but using AND as default operator narrows
the results with each added term, so the ranking is less noticeable
than it would be with "OR" queries. It doesn't look like the Grails
app is using the dis_max either.
> Replace query_string with simple_query_string

- app/main/services/query_builder.py
- tests/app/services/test_query_builder.py
- tests/app/views/test_search.py
[#98468022](https://www.pivotaltracker.com/story/show/98468022)
Hightlighted fragments are wrapped in html tags, which makes it hard
for the buyer-frontend to escape any html entities in the original
service field. Setting elasticsearch "highlight" `encoder` to `html`
makes it encode HTML in the original field data before adding
highlighting tags. This way buyer-frontend can treat highlighted
strings as safe without any additional escaping.
(https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html#_encoder)
> Escape HTML in "highlight" search results text

- .ebextensions/indexupdate.config
- app/__init__.py
- app/main/services/process_request_json.py
- app/main/services/query_builder.py
- app/main/services/search_service.py
- app/mapping.py
- application.py
- config.py
- mappings/services.json
- requirements.txt
- setup.cfg
- tests/app/helpers.py
- tests/app/services/test_process_request_json.py
- tests/app/services/test_query_builder.py
- tests/app/views/test_search.py
- tests/app/views/test_search_queries.py
- tests/app/views/test_status.py
Datacentre Tier is one of the filters shown in the buyer-frontend,
so it should be indexed and accepted as a filter field.
Right now adding a field requires adding it to the list of fields
and to the mapping attached to the index. The existing index mapping
is not affected by the mapping.json change.
"lot" is both a text and a filter field, so it should have both
definitions in the index mapping. Right now, "filter_lot" is created
dynamically by Elasticsearch when the field is first encountered on
document insert.
Previous version of the filter builder would group OR filter values
inside a single `bool` `"should"` list, which means a document only
needed to match any of the combined list of values, not at least one
value per OR filter field.
Instead, OR filters now return a single "terms" …
> Add datacentreTier field and fix OR filter search

- app/status/views.py
- tests/app/views/test_status.py
Checks app is up without hitting depencies if passed a ?ignore-dependencies query param. For use in ELB load balancers
> Added no dependecy elb status page check

- .ebextensions/apache_log.config
- .ebextensions/cwl-logs-apache-access.config
Create a new Apache access log with type and application information in
so that we can distinguish where a log message has come from. The
CloudWatch metric filters are applied to all messages in a log group and
seeing as we put all our log streams in the same group so that we can
easily search over them this means our alarms do not work properly.
This change also updates the alarm descriptions to be a bit more
helpful. They now say which application and environment the alarm came
from and link to the manual explaining what should be done.
See:
alphagov/digitalmarketplace-api#174 
alphagov/digitalmarketplace-api#175
alphagov/digitalmarketplace-api#176
alphagov/digitalmarketplace-api#177
> Use custom access log for CloudWatch

- .ebextensions/apache_log.config
- .ebextensions/cwl-logs-apache-access.config
Only fire the alarm if the rate of 400 - 403s goes over the limit. 404s happen quite frequently and are not indicative of anything going wrong.
This cannot be tested locally although it has been implemented on the data API and is working well. Rather than spinning up a new environment I'd like to test this on preview.
cc/ @minglis
> Make the 4xx apache logs alarm more specific

- app/main/services/query_builder.py
- tests/app/services/test_query_builder.py
- tests/app/views/test_search.py
**This fixes a problem whereby the entire service summary for G5 services (some of which have really long summaries) would be returned in the search results if no search terms were specified.**
***
Highlight excerpts for all service fields returned from elasticsearch now 400 character limit. This is enforced whether or not a search term has been found.
If no search term is found, up to the first 400 characters of the field will be used as the basis for the `highlight` snippet.
elasticsearch tries not to break in the middle of a word.  From the documentation: 
> The actual length may be shorter than specified as it tries to break on a word boundary.
Trailing punctuation is also removed.
Roughly approximates our 50-word limit on service summaries for G6+ services.
More information about …
> [#99425224] Add rough word limit on es highlight excerpts

- .ebextensions/cwl-logs-application.config
- requirements.txt
This is the same change that has been implemented on the other applications.
See: https://github.com/alphagov/digitalmarketplace-api/pull/225
> Add application JSON logs to CloudWatch logs

- app/main/services/query_builder.py
- tests/app/views/test_search.py
This is the semantically appropriate element:
> The HTML Mark Element (`<mark>`) represents highlighted text, i.e., a run of text marked for reference purpose, due to its relevance in a particular context. For example it can be used in a page showing search results to highlight every instance of the searched-for word.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/mark
It is also the element used on GOV.UK search results:
https://github.com/alphagov/frontend/blob/6711d367ec026c74c45b87e8ca8ceeda52396576/app/assets/stylesheets/views/_search.scss#L137
> Use <mark> element for highlighting search results

- mappings/services.json
- tests/app/views/test_search.py
- tests/app/views/test_search_queries.py
[#103575496](https://www.pivotaltracker.com/story/show/103575496)
Changes the serviceSummary mapping to make Elasticsearch use `postings`
highlighter for the service description field. Postings highlighter
fixes bugs with the unhighlighted document HTML escaping and fragment
size limits.
(https://www.elastic.co/guide/en/elasticsearch/reference/2.0/search-request-highlighting.html#postings-highlighter)
The default "plain" highlighter ignores the encoder option when nothing
was highlighted in the output, returning the truncated field text with
unescaped HTML entities, which creates an XSS vulnerability in search
results.
We could ignore the highlighter result and instead escape the original
description ourselves in this case, but we also use the highlighter to
limit the search result …
> Use postings highlighter for the serviceSummary field

- .ebextensions/apache_log.config
Request headers are only set on requests to the API from the frontend
apps, but response headers are set by a WSGI middleware for all
responses.
> Use response headers to log requestId from apache

- .ebextensions/indexupdate.config
- README.md
- app/main/services/response_formatters.py
- app/main/services/search_service.py
- app/main/views/search.py
- example_es_responses/index_info.json
- mappings/services.json
- tests/app/helpers.py
- tests/app/services/test_response_formatters.py
- tests/app/views/test_search.py
- tests/app/views/test_search_queries.py
Allows creating aliases instead of indexes using the existing PUT
endpoint. PUT request would either create a new alias or replace
an existing one with an alias to a given target.
PUT /<name> now expects a JSON payload with "type" key.
"type" could be "index" or "alias".
DELETE endpoint only supports indexes at the moment and there's no
way to delete an alias.
Adds information about index aliases and mapping version to the
index status response and the /_status endpoint.
Moved /index-name/status endpoint to /index-name.
Mapping version is stored in the mapping "_meta" field and should be
manually changed each time the mapping is modified.
Automatic migration will fail if there's a conflict in the mapping
update. Since resolving a conflict requires a reindexing it should
be done outside …
> [#103675320] Add create alias action to the /<name> PUT endpoint

- mappings/services.json
- tests/app/views/test_search.py
Postings highlighter doesn't support fragment_size options and
will always return one sentence if `no_match_size` is set. Search
result size can only be controlled by setting the number of sentences
that will be returned for each result, which is less precise than
the character limit we have now.
Switching to fvh keeps the existing search snippet size settings
while fixing the encoding issue caused by the plain highlighter.
> Use Fast Vector Highlighter for serviceSummary field

- app/main/services/response_formatters.py
- app/main/views/search.py
- tests/app/views/test_search.py
Deleting an alias using `es.indices.delete` deletes the underlying
index instead. To avoid accidental deletion index status is checked
first:
* If index name points to an alias, delete request fails with 400.
Aliases should be changed using the PUT endpoint.
* If index HAS an alias, delete request fails with 400. This is a
safety measure to avoid accidental deletion of indexes that are
being used by the application.
* Otherwise, the result of the index deletion request is returned.
> Disable deleting an alias or aliased index directly

- app/main/services/query_builder.py
- tests/app/services/test_query_builder.py
- tests/app/views/test_search.py
Until now, we've truncated the search summary text for each search result to 400 characters. Now there are no G5 services on production there is now reason to do so.
https://www.pivotaltracker.com/story/show/109270496
`no_match_size` is set because elasticsearch will only return highlight data if a match is found in one of the fields searched (set in `mappings/services.json`).
We need the summary text for each search result to be a copy of the `searchSummary` field in the `highlights` data so any HTML it contains is escaped (by setting the [encoder](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-highlighting.html#_encoder) to 'html'). 
(See https://github.com/alphagov/digitalmarketplace-search-api/blob/master/app/main/services/query_builder.py#L34)
Setting …
> Remove service description text truncation

- README.md
Latest version of elasticsearch(2.x.x) is posing a problem specifying the version that works to be used during install
> Update README-install specific version of elasticsearch

- .travis.yml
- Makefile
- README.md
- requirements_for_test.txt
- scripts/run_tests.sh
Add Makefile and switch to pytest, brings the search API in line with the other apps.
Be really clear about elasticsearch version
> Add makefile and switch to pytest

- README.md
The previous example just returned 404. This seems to work much better.
> Updates README to include a working example for local search api

- requirements_for_test.txt
- setup.cfg
We set py.test norecursedirs for other repos to stop py.test from gathering test files inside virtualenv folder when using local virtualenv (as opposed to the one installed by virtualenvwrapper)
Test files are still importing nose.tools even though we're using py.test as a test runner now.
This didn't cause an issue with Travis since Travis environments seem to have nosetools preinstalled.
> Fix venv test failures

- README.md
- app/authentication.py
- config.py
- scripts/run_app.sh
- scripts/run_tests.sh
- tests/app/helpers.py
- tests/app/views/test_search_queries.py
Removes the need to set environment variables with a list of tokens when running the search-api locally, similar to how this works in the Data API.
Also replaces test authentication setup/teardown with a test config tokens value.
> Read dev and test auth tokens from the app config

- config.py
Flask only looks up environment variables for flags defined in the config, so to get the production environment to be applied the key should have an initial value in the common preview, staging and production config.
> Set initial DM_SEARCH_API_AUTH_TOKENS value to None

- .ebextensions/packages.config
We've added cffi to requirements.txt for PaaS, since dmutils depends
on it.
PaaS requires specifying python dependencies that require a C library
in the application requirements.txt, which it parses to install the
required system packages.
For Elastic Beanstalk we need to specify the list of packages
manually in .ebextensions
> Install libffi-dev on the ElasticBeanstalk environments

- application.py
When upgrading dmutils I've copied the new `init_manager` code from
the API but forgot to update the port.
Also adds mappings to the list of watched locations for the development
server, so the app will restart if the files are modified.
> Fix local search-api port to 5001

- mappings/services.json
- tests/app/services/test_query_builder.py
- question name changed between G-Cloud-8 and G-Cloud-9
- we'll need to remove the old 'service types' filter at some point after
go-live.
https://trello.com/b/yXdcOenW/g9-catalogues-sprint-in-progress
> Add service categories filter.

- README.md
elasticsearch 1.x is no longer available via homebrew
> Updated installation instructions for elasticsearch

- .dockerignore
- Dockerfile
- Makefile
Adds Dockerfile and a make build-docker task.
New image is build on the base-api image, which has the ONBUILD
commands required to install api dependencies and copy the app
files.
This also adds a whitelist dockerignore. By default, docker will
use everything in the current directory (including eg .git) as
the build context and since our base images use `COPY .` the files
end up in the public container.
To avoid accidentally pushing any sensitive / modified files we're
using the .dockerignore as a whitelist: it will only copy the files
that are matched by the `!...` patterns.
Any new top-level files or directories used either during the app
runtime or the docker build process will need to be added to the
.dockerignore list or they won't be accessible from the image.
> Set up docker image build

- Dockerfile
- app/__init__.py
- requirements.txt
Adds support for passing additional arguments to Elasticsearch
constructor using `app_init` `kwargs`.
By default Python elasticsearch client 1.x sets verify_certs to
False, which means it doesn't verify TLS certificates when connecting
to Elasticsearch over HTTPS and urllib3 prints an InsecureRequestWarning
on each request.
Setting `verify_certs=True` explicitly removes the warning and prevents
connections if the certificate doesn't validate.
Moves awslogs agent logs to a file
> Fix insecure request warning

- app/main/services/query_builder.py
- app/main/services/search_service.py
- app/main/views/search.py
- app/mapping.py
- mappings/services.json
- tests/app/services/test_query_builder.py
- tests/app/views/test_search_queries.py
This adds an endpoint to retrieve services aggregated by certain characters (e.g. lot and category) for use in G-Cloud search. The aggregated fields are detected based on the presence of a 'raw' multifield in the ES mapping; when we look at ES in more depth we should consider bringing the magic `filter_` fields under this same construct for the sake of simplicity.
Ripped out some real weirdness in the tests...
https://trello.com/c/5LRAkydD/481-show-number-of-services-within-category
> Add aggregations endpoint

- mappings/services.json
We want to be a little forgiving with user's search terms so that they don't miss relevant services if they're searching with a word in the wrong form (e.g. `hosted` instead of `hosting`). Therefore we'll apply a light stemming algorithm to search terms to collapse them to a root form (e.g. `hosting`/`hosted` will be reduced to `host` and indexed/searched against that term).
We will apply this against our main full-text service-specific fields: description, features, benefits, and as a bonus, categories (where it's easy to imagine users may search using a mutation of our term).
https://trello.com/c/Y6rdUgxU/517-search-stemming
> Add stemming

- .travis.yml
- Dockerfile
- Makefile
For this trello card: [https://trello.com/c/VH7lBFc5](https://trello.com/c/VH7lBFc5)
To upgrade the app to Python 3 we just need to pull in the Python 3
version of the base-api docker image. This is from version 2.0.0
onwards.
We also upgrade Travis to test with Python 3.6 to reflect the Python
version being used in the base image.
All unit tests are passing with 3.6, and the functional tests pass 
locally; master and jenkins branches.
> Update to Python 3.6

- app/main/services/query_builder.py
- app/main/services/search_service.py
- config.py
- tests/app/views/test_search.py
When we lock a Direct Award project we need to retrieve the list of matching services for a given search. We only care about the ID of the service, not the content. Let's add a switch on search endpoint to only return matching service IDs. If we do this, increase page size as the data returned will be greatly reduced.
https://trello.com/c/gs2I3Cj2/676-end-your-search
> Retrieve only service IDs for a search

- .gitignore
- default.nix
- local.example.nix
- setup.cfg
Adds a `default.nix` file for the search-api, copied from the digitalmarketplace-api version. Updates .gitignore to ignore the venvs that nix generates.
> Add default.nix for search-api (copied from dm-api)

- app/main/services/process_request_json.py
- app/main/services/search_service.py
- app/mapping.py
- mappings/services.json
- tests/app/services/test_process_request_json.py
- tests/app/services/test_query_builder.py
- tests/app/views/test_search.py
- tests/fixtures/mappings/services.json
Add a new field to each document (a hash of the serviceId) that will allow tiebreaking results that have the same score to give random (but consistent) ordering. We will not actually _use_ the tiebreaker field yet as we need to re-index all stages with the new mapping before we can start to utilise it in a follow-up PR.
https://trello.com/c/RyS8rrIc/20-search-ordering-bug-small
> Add new field (hash of service ID) to each indexed document

- app/main/services/query_builder.py
- tests/app/services/test_query_builder.py
- tests/app/views/test_search.py
Follow-up PR to https://github.com/alphagov/digitalmarketplace-search-api/pull/107 which starts using the added field to sort results. We order by term `_score` first, and if those are equal, tiebreak using the hash to give consistent result ordering.
This PR only consists of the single commit but sits on top of PR 107 above, so the change view contains more than this actually implements. Look here for the commit changes: https://github.com/alphagov/digitalmarketplace-search-api/pull/108/commits/7e54a3380eb4b32c61baf0656b025cb3b9f886b8
https://trello.com/c/RyS8rrIc/20-search-ordering-bug-small
> Order results by score and tiebreaker

- app/main/views/search.py
- tests/app/views/test_search.py
This fixes the uncaught application exception: 
```
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.6/site-packages/flask/_compat.py", line 33, in reraise
raise value
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/lib/python3.6/site-packages/flask/app.py", line 1461, in dispatch_request
return …
```
> Catch 'N/A' connection error and 500

- app/mapping.py
- tests/app/views/test_search.py
Produce comprehensible error when client attempts to use wrong doctype.
- when we can't find the mapping, a 400 will do.
https://trello.com/c/5oIKvS1s/100-search-service-for-briefs-plus-indexing-script
> Wrong doctype 400

- README.md
The PUT example used the URL which may seem to someone unfamiliar
with the repo to be a legitimate URL that should be used - however
it was only an example. Hopefully now it is clearer that the user
should create the URL themselves using a desired index name.
> Update README so clear on which variable should be changed

- app/main/services/process_request_json.py
- mappings/briefs-digital-outcomes-and-specialists-2.json
- tests/app/services/test_process_request_json.py
Part of this ticket: https://trello.com/c/KcqU7k20
A transformation to conditionally update the value of a field.
This is being created so that the value of the status field for a brief
being indexed can be changed from 'cancelled', 'withdrawn' or 'awarded' to
just 'closed'.
We will be rolling out the new statuses, but for now we just want to
maintain existing functionality.
>  Add `update_conditionally` transformation

- app/main/services/response_formatters.py
- app/main/services/search_service.py
- app/main/views/search.py
- tests/app/services/test_response_formatters.py
- tests/app/views/test_search.py
- tests/app/views/test_search_queries.py
Part of this ticket: https://trello.com/c/KcqU7k20
We want to be able to filter my status on the frontend, and so we need
this in the mapping.
When searching, the data that was being returned was behind a `services`
key. This updates to a more generic `documents`.
> Add `filter_status` to briefs mapping and return documents instead of services 

- .flake8
- requirements-dev.txt
- scripts/index-g6-in-elasticsearch.py
Add flake8 per-file-ignores, in place of flake8-putty, so that we can support newer Python3 syntax like eg f-strings and type annotations.
Flake8 report:
```
/Users/samuelwilliams/git/digitalmarketplace-search-api/venv/bin/flake8 .
./scripts/index-g6-in-elasticsearch.py:90:1: E305 expected 2 blank lines after class or function definition, found 1
make: *** [test-flake8] Error 1
```
> Change from flake8-putty to per-file-ignores

- mappings/briefs-digital-outcomes-and-specialists-2.json
Within a status, we want to sort briefs in descending chronological
order, so that new briefs appear higher up the list.
As the list of fields to sort by is passed directly to elasticsearch, we
can use elasticsearch syntax to change this ordering. This is what we've
done here.
> Sort briefs by publishedAt descending

- app/main/services/response_formatters.py
- tests/app/views/test_update.py
- tests/conftest.py
In `api_response` we were catching `TypeErrors` when checking the status
code returned from elasticsearch. Elasticsearch has a weird thing where
it can return 'N/A' as the status code.
Previously we were checking if the status code was 'N/A' and handling it
if it was. If it wasn't we just reraised the TypeError.
This meant that we lost any info about the error returned by
Elasticsearch, and only got the stack trace leading to the TypeErrorin
the app.
We had a bunch of 500's caused by this, as Elasticsearch returned
something with a string as it's status code that wasn't 'N/A'. Due to
our lack of logging we don't know what it was.
This update will allow us to handle any string status codes, and log
them so we know what they are.
> Handle and log string status codes

- mappings/briefs-digital-outcomes-and-specialists-2.json
- mappings/services.json
- tests/fixtures/mappings/services.json
Following on from https://github.com/alphagov/digitalmarketplace-frameworks/pull/492
Story https://trello.com/c/2wYwttWZ/171-500s-on-buyer-frontend-for-g-cloud-search-page-numbers-above-100
include similar change to test fixture mapping as better assurance that
this is consequence-free.
> services mapping: update, including max_result_window setting

- app/main/services/search_service.py
- tests/app/helpers.py
- tests/app/views/test_admin.py
- tests/app/views/test_update.py
Trello https://trello.com/c/2wYwttWZ/171-500s-on-buyer-frontend-for-g-cloud-search-page-numbers-above-100
The existing implementation had the flaw that it failed to update the `settings` accompanying an updated mappings file. Fixing that proves to be quite tricky, mostly because ES will refuse to accept the attempted setting of "static" `settings` on a live index, even if they are unchanged from their previous values. This means we must determine which settings don't match those already on the index, as attempting to put any of them that are considered "static" would needlessly cause the update to fail. The difficulty in doing *that* comes from ES's habit of allowing deep-nested json object references `to.be.specified.like.this`, and in places allowing omission of levels of the nesting …
> remove ability to update index mapping through attempting to "create" an existing index

- app/__init__.py
https://trello.com/c/fTjMGMix/185-paas-elasticsearch-vcapservices-changing
PaaS will shortly support multiple ES host URIs, for high availability (fingers crossed this has already happened, but it's being tested first before we switch to it).
This shouldn't require any changes to the Search API itself, just which key of the PaaS config we get the host URI(s) from. The Python elasticsearch client can happily cope with either a single host or a list of hosts.
For this PR I've put in a `try...except` to fall back to the old key, but this may be overkill. Thoughts welcome!
> Use multiple ES host 'uris' field from PaaS config

- app/main/services/query_builder.py
- app/main/services/search_service.py
- tests/app/views/test_search.py
Trello https://trello.com/c/kp4fXdEC/310-search-pages-still-500-instead-of-404ing
This introduces a few tricks to detect a couple of cases where we should be returning a 404:
* Firstly, catch situations where a 500 is returned because `max_result_window` is exceeded. in most cases these should be treated as a 404 but only after we've checked that we are actually requesting a page that wouldn't exist given the result count or whether we just haven't set the `max_result_window` high enough for this index. it does mean firing off another request just to be able to categorize the error, but that's probably worth it to be able to return something sane (and leave something less alarming in our logs).
* Additionally, return 404 in regular cases where a page is requested that is beyond the number …
> Return 404s in (hopefully) all cases where a page beyond the available results is requested

- mappings/briefs-digital-outcomes-and-specialists-2.json
Trello https://trello.com/c/Ng8G6f9K/294-suppliers-can-view-date-questions-close-on-dos-search-page
Added as a simple "keyword" field as we only care about it being returned in the results.
> briefs mapping: add `clarificationQuestionsClosedAt` field

- .flake8
- app/main/services/search_service.py
When handling a `TransportError` from Elasticsearch, if the error is a
`ReadTimeoutError` it will not have the attribute `error` therefore we
get the following stack trace:
```
AttributeError: 'ReadTimeoutError' object has no attribute 'get'
```
We now catch the `AttributeError` and handle it accordingly.
https://trello.com/c/1AU0vQC4
> Handle readtimeout error

- mappings/briefs-digital-outcomes-and-specialists-2.json
Corresponding to https://github.com/alphagov/digitalmarketplace-frameworks/pull/499 and https://trello.com/c/qdNbRJ4e/331-supplier-can-search-for-buyer-on-dos
> briefs mapping: addition of text search

- mappings/briefs-digital-outcomes-and-specialists-2.json
We would like to show more detail about the status of an award in the search results for briefs. Currently the statuses are transformed in the search mapping to either 'open' or 'closed'.
We need to maintain the original status values for each brief in Elasticsearch whilst also retaining the current filtering ability.
This PR adds a brand new target field `statusOpenClosed` which will be used by the `buyer-frontend` to continue to filter on 'open' and 'closed' briefs. 
We are keeping the old transformations of the status field in place for the moment until the updates to the `buyer-frontend` have been made.
Corresponding PR:
https://trello.com/c/y59qiKOl/335-show-award-status-in-dos-search-results
> Add field for filtering open and closed briefs

- mappings/briefs-digital-outcomes-and-specialists-2.json
11.0.0 removes the transformation of status field. We now use `statusOpenClosed` to transform the brief statuses so they can be used by the DOS search filters.
https://trello.com/c/y59qiKOl/335-show-award-status-in-dos-search-results
> Use frameworks version 11.0.0

- app/status/views.py
- requirements-app.txt
- requirements.txt
- tests/app/views/test_status.py
The status endpoint for all of the apps is highly redundant across
repositories so I've moved it to dm-utils. We now only need to call this
method from the view stub in each app and pass in a couple of resources
(mainly the current_app and any api clients) to get a consistent status
JSON blob back.
https://trello.com/c/BBvu6eUk/383-ensure-healthcheck-endpoint-fails-if-low-disk-space
> Use centralised status method

- app/main/services/search_service.py
- tests/app/services/test_search_service.py
Search Kibana logs for requestId `88b88bbed572b0d7` will show an interesting error that wasn't handled properly by the search-api. This PR fixes the error handling to gracefully return and log the error.
https://trello.com/c/5yZ9RfNk/512-low-test-coverage-on-coresearchandaggregate
https://trello.com/c/DiBqpPZW/344-search-api-500-30-06-18-am
> Bugfix avoid resetting attribute e 2

- app/__init__.py
GOV.UK PaaS have recently changed the name of their elasticsearch service in preparation for migration.
This quick fix will work until elasticsearch-compose is withdrawn; a future solution should use a more robust way of determining the elasticsearch URI.
> Change the VCAP_SERVICE key for elasticsearch

- requirements-app.txt
- requirements.txt
It pulls in a temporary (hopefully) fix to not configure the
urllib3.util.retry logger for the search api.
The Elasticsearch client causes it to generate a lot of unnecessary
logs. We're going to put a PR in upstream and see if we can get it fixed
there, but we'll go with this for now.
> Bump utils to 40.9.1

- app/__init__.py
This commit fixes a bug found during the procees of migrating PREVIEW to 
elasticsearch from Aiven (see https://trello.com/c/k6OgT7v4/)
> If `uris` is not in VCAP_SERVICES check `uri`

- app/__init__.py
Change the application init so it takes different arguments from VCAP
services based on the service provider.
We detect the service provider based on the tags part of the service
object.
This code can be removed once migration is fully completed.
This is part of the [ElasticSearch migration ticket](https://trello.com/c/k6OgT7v4)
> Add a switch block to aid in migrating ElasticSearch provider

- app/__init__.py
- config.py
- requirements-app.txt
- requirements.txt
Trello https://trello.com/c/ZH9trgjH/419-snyk-alert-for-flask-010x-vulnerability
https://github.com/alphagov/digitalmarketplace-utils/pull/447
Nothing particularly exciting for this app.
> digitalmarketplace-utils dependency: bump to 43.0.0, remove featureflags references

- tests/app/test_application.py
The retry functionality is buried in the elasticsearch.transport.Transport class and
can be effected by passing max_retries to the elasticsearch.client.ElasticSearch object
(https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/client/__init__.py#L184)
or the flask_elasticsearch.FlaskElasticsearch.init_app method. This test is an attempt
to surface this behaviour.
> Add a test to indicate/ ensure that flask is performing retries 

- app/__init__.py
- requirements-app.txt
- requirements.txt
Upgrade to flask 1.0.2
* Update utils to 44.0.0
* Change imports from deprecated flask.ext to flask_  
> flask.ext - import extensions directly by their name instead of through the flask.ext namespace
http://flask.pocoo.org/docs/1.0/changelog/#version-1-0-2
https://trello.com/c/bBDir2Gp/18-flask-1x-upgrade
> 18 flask 1x upgrade

- requirements-app.txt
- requirements.txt
Trello: https://trello.com/c/rT3obXh5/543-check-whether-idna-dependency-in-antivirus-api-requirements-apptxt-can-be-unpinned
We no longer need to pin `idna`; `requests 2.21.0` removes the requirement for idna to be < 2.8.
(See equivalent PR for the antivirus-api: https://github.com/alphagov/digitalmarketplace-antivirus-api/pull/33)
> Unpin idna from requirements

- .travis.yml
I forgot to do this in #189.
The Travis tests should fail, due to the issue mentioned in #191. Once #191 is merged this can be safely merged.
> Update Elasticsearch version used by Travis CI

- mappings/services-g-cloud-10.json
Ticket: https://trello.com/c/uTA0PcGF
This commit updates the G-Cloud 10 service mapping using version 15.0.0 of the framework so that the deprecated Elasticsearch parameter `include_in_all` is removed (See alphagov/digitalmarketplace-frameworks#552 for more details).
This shouldn't actually make a difference to `search-api` as we never search using `_all`.
According to the readme, once this PR has been merged and released, the search-api still needs to be poked to tell it to change the Elasticsearch mapping; presumably this will also need a reindex.
> Remove deprecated `include_in_all`

- tests/app/helpers.py
- tests/app/services/test_process_request_json.py
- tests/app/services/test_query_builder.py
- tests/app/services/test_response_formatters.py
- tests/app/services/test_search_service.py
- tests/app/views/test_admin.py
- tests/app/views/test_meta.py
- tests/app/views/test_search.py
- tests/app/views/test_search_queries.py
- tests/app/views/test_update.py
- tests/conftest.py
This PR changes our tests to use the services mapping `services-g-cloud-10`.
To acheive this I refactored the tests so that the services mapping used in tests is defined in one place in `tests/conftest.py`; this should also mean that it is much easier to update the tests in future.
I also did some generic refactoring, including renaming some things so that their intended uses are clearer. A lot of these changes are part of the work to [prepare search-api for Elasticsearch 6](https://trello.com/c/BlYurEoJ/418-prepare-search-api-for-elasticsearch-6).
> Use G-Cloud 10 services mapping in tests

- tests/app/services/test_query_builder.py
- tests/app/services/test_search_service.py
- tests/app/test_application.py
- tests/app/views/test_admin.py
- tests/app/views/test_meta.py
- tests/app/views/test_search.py
- tests/app/views/test_search_queries.py
- tests/app/views/test_status.py
- tests/app/views/test_update.py
- tests/conftest.py
- tests/helpers.py
* Move `tests.app.helpers` > `tests.helpers`
* Remove `assert_response_status` in favour of normal assert statement
* Consolidate common setup method of TestSearchEndpoint and TestSearchResultsOrdering
* Create BaseSearchTestWithServices
* Remove `create_services` now only used in the consolidated setup
* Move `services_mapping` and `make_services` to `tests.helpers`
> Remove extraneous helper methods and move helpers to base of tests

- .travis.yml
- app/main/services/query_builder.py
- app/main/services/search_service.py
- requirements-app.txt
- requirements.txt
- tests/app/services/test_query_builder.py
- tests/app/views/test_admin.py
- tests/app/views/test_search.py
- tests/app/views/test_update.py
PR to [make search-api work with Elasticsearch 6](https://trello.com/c/BlYurEoJ/418-prepare-search-api-for-elasticsearch-6).
Tested with Elasticsearch 6.7.0.
Note that this merges into `elasticsearch-6` (not `master`).
Includes workaround for https://github.com/elastic/elasticsearch/issues/41066, but hopefully it won't be needed!
> Elasticsearch 6 support

- app/main/views/meta.py
- tests/app/views/test_meta.py
Fixes issue detailed on [Trello].
It turns out the 500s weren't caused by any change in our code, but a change in the default indices of the Elasticsearch instance provided by Aiven.
In the past there has been an index `.kibana-1`, which we have ignored in `app.main.views.root`, but in the new instance there is also an alias for this index, which our logic wasn't expecting and couldn't handle.
This PR adds a test for the expected behaviour and a fix.
[Trello]: https://trello.com/c/KW5wwTnv
> Fix bug where alias for .kibana-1 would cause 500

- .travis.yml
Ticket: https://trello.com/c/GCgD9vuB/781-remove-es5-travis-check-for-search-api
We no longer use Elasticsearch 5 anywhere, so we don't need this check.
> Remove Elasticsearch 5 Travis CI check

- Dockerfile
- default.nix
https://trello.com/c/PyDaRXEj
To get us https://github.com/alphagov/digitalmarketplace-docker-base/pull/56
Also sneak in a little nix fix.
> docker base image: bump to 4.5.4 

- mappings/services-g-cloud-11.json
https://trello.com/c/li12EojM/62-g-cloud-search-results-mapping-is-mis-categorising-a-filter
Commits the new search mapping generated by https://github.com/alphagov/digitalmarketplace-frameworks/pull/591.
The services will need a full re-indexing on production, so let's make sure we do a run of that on preview.
> Fix planningService mapping category

- app/__init__.py
- requirements-app.txt
- requirements.txt
- tests/app/test_application.py
This is an initial fix attempt for https://trello.com/c/Kd4qas51
It's not got any of the bells & whistles mentioned in the card involving "safe" headers or anything: the idea is to be able to release something that will let us know whether compressing our responses has _any_ effect on our envoy issues.
If we take this further, we can easily subclass this `Gzip` middleware to add e.g. header-controlled options and stick it in `-utils`.
> use Flask-gzip to compress all possible responses

- Dockerfile
Reverts alphagov/digitalmarketplace-search-api#235
> Revert "bump docker base image to 7.0.0"

- Dockerfile
This didn't turn out to be the culprit after all - the release process just caused a dodgy ES broker to give us dodgy creds.
> Revert "Revert "bump docker base image to 7.0.0""

- app/__init__.py
- requirements-app.txt
- requirements.txt
- tests/app/test_application.py
Note here I had to manually set `requirements.txt` back to werkzeug `0.15.6` because pip was insistent on bumping it to `0.16.0` despite our restriction in `-utils`. Though it _doesn't_ complain about unmet dependencies with this package set despite my ineterference, so I guess it's fine...? Not sure what's going on here but, y'know, pip sucks, so it doesn't surprise me tremendously.
> switch from direct flask_gzip use to DMGzipMiddleware

- .travis.yml
- requirements-app.txt
- requirements.txt
https://trello.com/c/GsDBHBo7/135-switch-on-python-37-and-38-travis-checks-to-check-potential-dependency-problems-before-upgrade
- Bumps utils only - other libraries not used
- Adds 3.7 and 3.8 to Travis config
(Also bumps Werkzeug, superseding https://github.com/alphagov/digitalmarketplace-search-api/pull/243)
> Add Python 3.7 and 3.8 checks to Travis

- requirements-app.txt
- requirements.txt
Update search api to use new utils including causing run of additional_checks regardless of `include-dependencies` parameter
See:
https://trello.com/c/B2GfZgfO/192-cause-additionalchecks-to-always-be-run-regardless-of-ignore-dependencies-on-status-endpoint
https://github.com/alphagov/digitalmarketplace-utils/blob/master/CHANGELOG.md#5100
> 192-cause-additionalchecks-to-always-be-run-regardless-of-ignore-dependencies-on-status-endpoint

- Dockerfile
bump docker version to pick up changes from alphagov/digitalmarketplace-docker-base#74
> bump docker image

- .travis.yml
- README.md
- app/main/services/search_service.py
- tests/app/views/test_search.py
Revert workarounds for https://github.com/elastic/elasticsearch/issues/41066 which has now been fixed in the version of elasticsearch we are running on PaaS.
I have also manually checked highlighting is still working e.g.
> Remove workarounds for elasticsearch highlighting bug

- config.py
I don't think there is a need to limit the number of results per page locally, it's better to have it closer to what will be seen on production where possible.
> Remove local DM_SEARCH_PAGE_SIZE configuration

- .travis.yml
- app/main/services/search_service.py
- app/main/views/meta.py
- app/mapping.py
- mappings/briefs-digital-outcomes-and-specialists-2.json
- mappings/services-g-cloud-10.json
- mappings/services-g-cloud-11.json
- mappings/services-g-cloud-12.json
- mappings/services.json
- requirements.in
- requirements.txt
- tests/app/views/test_admin.py
- tests/app/views/test_meta.py
- tests/helpers.py
Update the search API to support Elasticsearch 7. Our hosting provider has deemed ES6 EOL and will upgrade our current ES6 instances to ES7 on November 20th if we don't do it before then. 
This is effectively a **breaking change** - this version of the search API will not work on our existing ES6 instances as it expects changes to the index mappings which are not compatible with ES6. All API routes and data are the same however, so our API client will not need changing.
To migrate from the current search API and ES6 we'll need to follow a similar process to when we migrated to ES6 as detailed in [this card](https://trello.com/c/Yh8uyxvF/2102-migrate-elasticsearch-on-preview)
In order to make the API changes we have updated the mapping JSON files in this repo which are generated in [the …
> Support Elasticsearch 7

- mappings/briefs-digital-outcomes-and-specialists-2.json
- mappings/services-g-cloud-12.json
Ticket: https://trello.com/c/Yh8uyxvF/2102-migrate-elasticsearch-on-preview
Update the search mappings for DOS and G-Cloud 12 using the changes in
alphagov/digitalmarketplace-frameworks#653.
> Update search mappings from digitalmarketplace-frameworks@18.0.0

- .secrets.baseline
- requirements.in
- requirements.txt
- tests/app/test_application.py
Reverts alphagov/digitalmarketplace-search-api#303
This fails to deploy (https://ci.marketplace.team/job/release-app-paas/9217/consoleFull). This is because 7.14.0 dropped support for AWS Elasticsearch, which is what GOV.UK PaaS uses (https://github.com/elastic/elasticsearch-py/issues/1666)
`elasticsearch.exceptions.UnsupportedProductError: The client noticed that the server is not a supported distribution of Elasticsearch", "e": "500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.`
Let's revert to fix the build and then work out what we do about this.
> Revert "Bump elasticsearch from 7.13.4 to 7.14.0"

- .github/dependabot.yml
https://trello.com/c/s6V6B7Pv/2302-work-out-what-to-do-with-our-elasticsearch-client
Elastic have chosen to make their client incompatible with the hosted Elasticsearch we use (https://github.com/elastic/elasticsearch-py/issues/1666). So we can't take future updates without breaking things.
Snyk will warn us if there are any security issues with the current version.
> Ignore updates to elasticsearch
